### ISSUE TITLE
Performance against large document db collections

### ISSUE THREAD

**Issue by dvmorris** [Azure/azure-documentdb-hadoop#1]
We are having trouble getting this library to perform against a DocumentDB collection that has about 1.75 GB in it. For example, calculating an AVG of a single column is timing out on a 4 node HDInsight cluster. Has anyone tried using this library yet, and if so, are you having similar results? Perhaps we are not using it properly. 

Thanks,
Dave

**Comment by nomiero** [comment]
Hello Dave,

I have a few small questions to help me understand the issue more :
- Are you using version 0.9.1 jar ?
- Is the HDInsight cluster in the the same data center as the DocumentDB account ( that would make a big performance difference )?
- What is the value of the timeout ?

**Comment by dvmorris** [comment]
Thanks for getting back so quickly. 

We are using version 0.9.0 of the JAR. This is included at the top of our Hive queries:

```
add JAR wasb:///lib/azure-documentdb-0.9.3-jar-with-dependencies.jar; 
add JAR wasb:///lib/json-serde-1.3.1-SNAPSHOT-jar-with-dependencies.jar;
add JAR wasb:///lib/azure-documentdb-hadoop-0.9.0.jar; 
```

We are having trouble compiling the JAR from source with the following errors:

```
[INFO] 5 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.625 s
[INFO] Finished at: 2015-02-19T13:16:50-06:00
[INFO] Final Memory: 32M/317M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project a
zure-documentdb-hadoop: Compilation failure: Compilation failure:
[ERROR] /C:/Users/david.morris/Documents/GitHub/azure-documentdb-hadoop/src/com/microsoft/azure/documentdb/hive/Document
DBSerDe.java:[16,32] package org.openx.data.jsonserde does not exist
[ERROR] /C:/Users/david.morris/Documents/GitHub/azure-documentdb-hadoop/src/com/microsoft/azure/documentdb/hive/Document
DBSerDe.java:[17,37] package org.openx.data.jsonserde.json does not exist
[ERROR] /C:/Users/david.morris/Documents/GitHub/azure-documentdb-hadoop/src/com/microsoft/azure/documentdb/hive/Document
DBSerDe.java:[25,13] cannot find symbol
[ERROR] symbol:   class JsonSerDe
[ERROR] location: class com.microsoft.azure.documentdb.hive.DocumentDBSerDe
[ERROR] /C:/Users/david.morris/Documents/GitHub/azure-documentdb-hadoop/src/com/microsoft/azure/documentdb/hive/Document
DBSerDe.java:[29,30] cannot find symbol
[ERROR] symbol:   class JsonSerDe
[ERROR] location: class com.microsoft.azure.documentdb.hive.DocumentDBSerDe
[ERROR] /C:/Users/david.morris/Documents/GitHub/azure-documentdb-hadoop/src/com/microsoft/azure/documentdb/hive/Document
DBSerDe.java:[34,17] cannot find symbol
[ERROR] symbol:   class JSONObject
[ERROR] location: class com.microsoft.azure.documentdb.hive.DocumentDBSerDe
```

The DocumentDB container is actually in West US, and our cluster is in South Central. We are working on getting it moved to the correct data center. Thanks for point that out! 

Here is the error from our timeout issue:

```
Diagnostic Messages for this Task:
AttemptID:attempt_1424281348568_0032_m_000000_3 Timed out after 600 secs

FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
MapReduce Jobs Launched: 
Job 0: Map: 1  Reduce: 1   Cumulative CPU: 2080.825 sec   HDFS Read: 0 HDFS Write: 0 FAIL
Total MapReduce CPU Time Spent: 34 minutes 40 seconds 825 msec
```

**Comment by nomiero** [comment]
- If you are using HDInsight, one best option is to follow http://azure.microsoft.com/en-us/documentation/articles/documentdb-run-hadoop-with-hdinsight/ that will save you all the imports in the script and all the versioning errors.
- If you are not using HDInsight:

1 ) Please change the connector jar version to 0.9.1 and documentdb version to 0.9.4 because some memory leak issues were resolved in this upgrade ( note that documentdb version 0.9.4 is not shipped with dependencies )

2 ) The errors you get when building the jar can be avoided if you add the json serde jar to the pom dependencies after adding it to the local maven repo ( not a must though ), Alternatively you can get the jar directly from the releases tab in github https://github.com/Azure/azure-documentdb-hadoop/releases/tag/0.9.1

**Comment by dvmorris** [comment]
Thanks for these tips! This tutorial must be very new, because we were trying this on Tuesday and were not able to find it. We are using HDInsight, so we will try to follow your advice about the Script Action when creating the cluster in the future. 

Is there any way to setup this repository to compile correctly after cloning it, without having to do those extra manual steps? Or at least an example of how and where to change the POM file to make this process a little less tricky. I suppose it's not that important now that there is a PowerShell Script Action to take care of this part.

Thanks again for your help! I'm looking forward to trying out this new technique.

**Comment by nomiero** [comment]
Great, looking forward to hearing how it works for you :)
Unfortunately the manual steps are needed because the json serde jar is not available in Maven ( that's why we publish the jar in the releases tab )
We might do an example for how to build it if we find a required demand for it.

**Comment by dvmorris** [comment]
I see, thanks for the clarification!

**Comment by dvmorris** [comment]
I ran a test on a cluster in the same data center as the DocumentDB collection, and I get the following error:

```
15/02/19 22:06:35 WARN conf.HiveConf: HiveConf of name hive.log.dir does not exist
15/02/19 22:06:35 WARN conf.HiveConf: HiveConf of name hive.auto.convert.sortmerge.join.noconditionaltask does not exist

Logging initialized using configuration in file:/C:/apps/dist/hive-0.14.0.2.2.1.0-2340/conf/hive-log4j.properties
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/apps/dist/hadoop-2.6.0.2.2.1.0-2340/share/hadoop/common/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/apps/dist/hive-0.14.0.2.2.1.0-2340/lib/hive-jdbc-0.14.0.2.2.1.0-2340-standalone.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/apps/dist/hbase-0.98.4.2.2.1.0-2340-hadoop2/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Query ID = hdp_20150219220606_75cb3808-6283-4a38-9124-b68d20560ca6
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks determined at compile time: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=
In order to set a constant number of reducers:
  set mapreduce.job.reduces=
Starting Job = job_1424381728758_0006, Tracking URL = http://headnodehost:9014/proxy/application_1424381728758_0006/
Kill Command = C:\apps\dist\hadoop-2.6.0.2.2.1.0-2340\bin\hadoop.cmd job  -kill job_1424381728758_0006
Hadoop job information for Stage-1: number of mappers: 1; number of reducers: 1
2015-02-19 22:07:25,134 Stage-1 map = 0%,  reduce = 0%
2015-02-19 22:08:25,675 Stage-1 map = 0%,  reduce = 0%
2015-02-19 22:09:21,462 Stage-1 map = 100%,  reduce = 100%
Ended Job = job_1424381728758_0006 with errors
Error during job, obtaining debugging information...
Examining task ID: task_1424381728758_0006_m_000000 (and more) from job job_1424381728758_0006

Task with the most failures(4): 
-----
Task ID:
  task_1424381728758_0006_m_000000

URL:
  http://headnodehost:9014/taskdetails.jsp?jobid=job_1424381728758_0006&tipid=task_1424381728758_0006_m_000000
-----
Diagnostic Messages for this Task:
Error: java.lang.IllegalStateException: Exception not retriable
    at com.microsoft.azure.documentdb.BackoffRetryUtility.execute(BackoffRetryUtility.java:20)
    at com.microsoft.azure.documentdb.QueryIterable$1.hasNext(QueryIterable.java:98)
    at com.microsoft.azure.documentdb.mapred.hadoop.DocumentDBRecordReader.getProgress(DocumentDBRecordReader.java:69)
    at org.apache.hadoop.hive.ql.io.HiveRecordReader.getProgress(HiveRecordReader.java:71)
    at org.apache.hadoop.mapred.MapTask$TrackedRecordReader.getProgress(MapTask.java:216)
    at org.apache.hadoop.mapred.MapTask$TrackedRecordReader.moveToNext(MapTask.java:202)
    at org.apache.hadoop.mapred.MapTask$TrackedRecordReader.next(MapTask.java:185)
    at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:52)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:450)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:343)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: com.microsoft.azure.documentdb.DocumentClientException: Exception: Microsoft.Azure.Documents.RequestRateTooLargeException, message: {"Errors":["Request rate is large"]}, request URI: rntbd://***:14900/apps/8de498d9-49f2-4c96-851c-2ca5b9a201f9/services/***-ServerService-12/partitions/0/replicas/130688383411817070p
    at com.microsoft.azure.documentdb.GatewayProxy.maybeThrowException(GatewayProxy.java:248)
    at com.microsoft.azure.documentdb.GatewayProxy.performPostRequest(GatewayProxy.java:348)
    at com.microsoft.azure.documentdb.GatewayProxy.doSQLQuery(GatewayProxy.java:130)
    at com.microsoft.azure.documentdb.DocumentClient.doQuery(DocumentClient.java:1951)
    at com.microsoft.azure.documentdb.QueryIterable.fetchNextBlock(QueryIterable.java:179)
    at com.microsoft.azure.documentdb.QueryIterable$1$1.apply(QueryIterable.java:83)
    at com.microsoft.azure.documentdb.BackoffRetryUtility.execute(BackoffRetryUtility.java:14)
    ... 14 more


FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
MapReduce Jobs Launched: 
Stage-Stage-1: Map: 1  Reduce: 1   HDFS Read: 0 HDFS Write: 0 FAIL
Total MapReduce CPU Time Spent: 0 msec
```

**Comment by nomiero** [comment]
This seems like an actual bug in the connector now, sorry you have experienced this bug. 
A question to understand how the bug happened in order to be able to repro it.
Were you running other requests at the same time other than the hadoop connector to target the endpoint ?

**Comment by dvmorris** [comment]
Yes, as a matter of fact I was running two queries that both used the
document db connector at the same time. One finished and one errored out.

**Comment by nomiero** [comment]
Got it, thanks a lot for this important feedback and sorry for running into this.
The issue happened because of the two connector instances running.
We are working on a fix for this issue and will be getting back to you very soon, thanks for your patience.

**Comment by dvmorris** [comment]
Is there any reason to create a Hive-managed table using this library, or is this exclusively for External tables?

**Comment by nomiero** [comment]
Managed hive table wouldn't make sense if you want to do hive jobs directly on the data.
If you want to have a managed table, you would need to first create an external table that points to documentdb endpoint, create another managed table and then copy all data from external table to the managed table and that wouldn't be useful unless you want to have a copy of your data to run jobs on.

I'm curious what would be a scenario for usage of Managed table with documentdb ?

**Comment by nomiero** [comment]
Hey Dvmorris, 
Sorry for getting back late on the issue, the new release 0.9.2 fixes the issue.
Also if you want to create an hdinsight cluster with the new release use the script: 
https://portalcontent.blob.core.windows.net/scriptaction/documentdb-hadoop-installer-v02.ps1 
Please let us know if you encounter any issues with the new release.
